config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  filter :locale

  root "main#index"

  scope module: "home" do
    resources :user_sessions, only: [:new, :create]
    resources :users, only: [:new, :create]
    get "login" => "user_sessions#new", :as => :login

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider

    get "events" => "events#index"
  end

  scope module: "dashboard" do
    resources :user_sessions, only: :destroy
    resources :users, only: :destroy
    post "logout" => "user_sessions#destroy", :as => :logout
    get "logout" => "user_sessions#destroy"

    resources :cards
    match "search-photo", to: "cards#search_photo", via: [:patch, :post]
    get "remote_cards" => "cards#remote"
    post "remote_create" => "cards#remote_create"

    resources :blocks do
      member do
        put "set_as_current"
        put "reset_as_current"
      end
    end

    put "review_card" => "trainer#review_card"
    get "trainer" => "trainer#index"

    get "profile/:id/edit" => "profile#edit", as: :edit_profile
    put "profile/:id" => "profile#update", as: :profile
  end
end

app/models/card.rb
require 'super_memo'

class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :block
  validates :user_id, presence: true
  before_validation :set_review_date_as_now, on: :create
  validate :texts_are_not_equal
  validates :original_text, presence: true
  validates :translated_text, :review_date, presence: true
  validates :user_id, presence: true
  validates :block_id, presence: true
  validates :interval, :repeat, :efactor, :quality, :attempt, presence: true

  mount_uploader :image, CardImageUploader

  scope :pending, -> { where('review_date <= ?', Time.now).order('RANDOM()') }
  scope :repeating, -> { where('quality < ?', 4).order('RANDOM()') }

  def check_translation(user_translation)
    distance = Levenshtein.distance(full_downcase(translated_text),
                                    full_downcase(user_translation))

    sm_hash = SuperMemo.algorithm(interval, repeat, efactor, attempt, distance, 1)

    if distance <= 1
      sm_hash.merge!({ review_date: Time.now + interval.to_i.days, attempt: 1 })
      update(sm_hash)
      { state: true, distance: distance }
    else
      sm_hash.merge!({ attempt: [attempt + 1, 5].min })
      update(sm_hash)
      { state: false, distance: distance }
    end
  end

  def self.pending_cards_notification
    users = User.where.not(email: nil)
    users.each do |user|
      if user.cards.pending.any?
        CardsMailer.pending_cards_notification(user.email).deliver_later
      end
    end
  end

  protected

  def set_review_date_as_now
    self.review_date = Time.now
  end

  def texts_are_not_equal
    if full_downcase(original_text) == full_downcase(translated_text)
      errors.add(:original_text, :texts_are_not_equal_notice)
    end
  end

  def full_downcase(str)
    str.mb_chars.downcase.to_s.squeeze(' ').lstrip
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :require_login
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_authenticated
    redirect_to login_path, alert: t(:please_log_in)
  end

  def not_found
    flash[:alert] = t(:not_found_alert)
    redirect_to root_path
  end
end

app/controllers/dashboard/blocks_controller.rb
class Dashboard::BlocksController < Dashboard::BaseController
  before_action :set_block, only: [:destroy, :edit, :update, :set_as_current,
                                   :reset_as_current]
  respond_to :html

  def index
    @blocks = current_user.blocks.all.order('title')
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def create
    @block = current_user.blocks.build(block_params)
    if @block.save
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      respond_with @block
    end
  end

  def destroy
    @block.destroy
    respond_with @block
  end

  def set_as_current
    current_user.set_current_block(@block)
    redirect_to blocks_path
  end

  def reset_as_current
    current_user.reset_current_block
    redirect_to blocks_path
  end

  private

  def set_block
    @block = current_user.blocks.find(params[:id])
  end

  def block_params
    params.require(:block).permit(:title)
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < Dashboard::BaseController
  before_action :set_card, only: [:destroy, :edit, :update]
  respond_to :html, :json

  def index
    @cards = current_user.cards.all.order('review_date')
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      @card.update(remote_image_url: card_params[:remote_image_url])
      ahoy.track "card:created"
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path
    else
      respond_with @card
    end
  end

  def destroy
    @card.destroy
    respond_with @card
  end

  def search_photo
    render layout: false
  end

  def remote
    render
  end

  def remote_create
    if RemoteWordsJob.perform_now(remote_params, current_user)
      ahoy.track "remote_cards:created"
      redirect_to cards_path
    end
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date,
                                 :image, :image_cache, :remove_image, :block_id,
                                 :search_string, :id, :remote_image_url, :photo)
  end

  def remote_params
    params.permit :remote_url, :row_selector,
                  :original_selector, :translate_selector
  end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < Dashboard::BaseController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path,
                  notice: t(:user_updated_successfully_notice)
    else
      respond_with current_user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :locale)
  end
end

app/controllers/dashboard/trainer_controller.rb
class Dashboard::TrainerController < Dashboard::BaseController

  def index
    find_card params[:id]
  end

  def review_card
    @card = current_user.cards.find(params[:card_id])

    check_result = @card.check_translation(trainer_params[:user_translation])

    if check_result[:state]
      if check_result[:distance] == 0
        flash[:notice] = t(:correct_translation_notice)
        ahoy.track "card:success_review"
      else
        flash[:alert] = t 'translation_from_misprint_alert',
                          user_translation: trainer_params[:user_translation],
                          original_text: @card.original_text,
                          translated_text: @card.translated_text
      end
      redirect_to trainer_path
    else
      flash[:alert] = t(:incorrect_translation_alert)
      ahoy.track "card:fail_review"
      redirect_to trainer_path(id: @card.id)
    end
  end

  private

  def trainer_params
    params.permit(:user_translation)
  end
end

app/controllers/dashboard/user_sessions_controller.rb
class Dashboard::UserSessionsController < Dashboard::BaseController
  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < Dashboard::BaseController
  def destroy
    current_user.destroy
    redirect_to login_path, notice: t(:user_deleted_successfully_notice)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/dashboard/cards/_flickr_widget.html.erb
<div class="flickr">
  <ul>
    <% photos.each.with_index do |row, row_index| -%>
      <li>
        <% row.each.with_index do |photo, index| %>
          <%= link_to(image_tag(photo.url(:small), :class => 'flickr_photo',
            			   :title => photo.title, :border => 0),
                     "#", :id => "photo_#{ row_index}_#{index}")  %>
        <% end %>
      </li>
    <% end -%>
  </ul>
</div>

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for card do |f| %>
  <div class="form-group">
    <%= f.input :original_text,  as: :text, label: t(:original_text_label),
                input_html: { class: 'form-control', required: true,
                              autofocus: true } %>
  </div>

  <div class="form-group">
    <%= f.input :translated_text,  as: :text, label: t(:translated_text_label),
                input_html: { class: 'form-control', required: true } %>
  </div>

  <div class="form-group">
    <%= f.input :image, as: :file, label: t(:image_label) %>
    <%= f.input :image_cache, as: :hidden %>
    <%= f.input :id, as: :hidden %>
  </div>

  <%= f.simple_fields_for :photo do |photo_form| %>
    <div class="form-group">
      <%= link_to 'Загрузить фото с Flickr', '#',
        class: 'btn btn-default', id: 'show_div' %>
      <div id="hidden" class="form-group">
        <%= photo_form.text_field :search_string, :value => params[:search_string] %>
      </div>
    </div>

    <div class="form-group">
      <%= photo_form.submit 'Искать фото', formaction: search_photo_path,
        class: 'btn btn-default', id: 'search_btn' %>

    </div>
  <% end %>

  <div id="flickr-photo">
  </div>

  <%= f.input :remote_image_url, as: :hidden %>

  <div class="form-group">
    <%= f.input :block_id, collection: current_user.blocks.all.order('title'),
                prompt: t(:select_deck), label: t(:decks_label),
                input_html: { class: 'form-control', required: true } %>
  </div>

  <p>
  </p>
  <% if card.image? %>
    <div class="form-group">
      <%= f.input :remove_image, as: :boolean, label: t(:delete_image) %>
      <div class="row">
        <div class="col-xs-6 col-md-4 card_image">
          <p class="thumbnail">
            <%= image_tag card.image_url %>
          </p>
        </div>
      </div>
    </div>
  <% end %>

  <%= f.button :submit, t(:save), class: 'btn btn-default' %>
<% end %>

app/views/dashboard/cards/edit.html.erb
<h2><%= t(:edit_card_label) %></h2>
<%= render 'form', card: @card %>

app/views/dashboard/cards/index.html.erb
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th><%= t(:original_text_label) %></th>
    <th><%= t(:translated_text_label) %></th>
    <th><%= t(:review_date) %></th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
  <% @cards.each do |card| %>
    <tr class="table table-hover table-condensed">
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime('%d.%m.%Y %H:%M:%S') %></td>
      <td><%= link_to t(:edit), edit_card_path(card) %></td>
      <td><%= link_to t(:delete), card, method: :delete,
                      data: { confirm: 'Удалить запись?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/dashboard/cards/new.html.erb
<h2><%= t(:add_card_label) %></h2>

<%= render 'form', card: @card %>

app/views/dashboard/cards/remote.html.erb
<%= form_tag "remote_create" do %>
  <div class="form-group">
    <%= label_tag :remote_url, t(:remote_url_label) %>
    <%= text_field_tag "remote_url", "", class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= label_tag :row_selector, t(:row_selector_label) %>
    <%= text_field_tag "row_selector", "", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :original_selector, t(:original_selector_label) %>
    <%= text_field_tag "original_selector", "", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :translate_selector, t(:translate_selector_label) %>
    <%= text_field_tag "translate_selector", "", class: "form-control" %>
  </div>

  <div class="form-group">
  </div>
  <%= submit_tag(t(:load), class: "btn btn-default") %>
<% end %>

app/views/dashboard/cards/search_photo.html.erb
<%= render partial: '/dashboard/cards/flickr_widget',
locals: { photos: FlickrPhoto.render(params[:card][:photo][:search_string]).in_groups_of(2) } %>